### ISSUE TITLE
Implement Dueling Dags

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#671]
Design Doc: https://dusty-lancer-e6c.notion.site/Simplified-DD1-1ed242a8c1094d9ca3734c46d65ffce4

This is a tracking bug with individual tasks. If a task needs further discussion please break it into its own issue.

- [x] Implement `dag.LazyStore` @grgbkr (7bc6106)
  - [x] Use LRU based on `getSizeOfValue`? @grgbkr (7bc6106)
- [x] integrate  `dag.LazyStore` @grgbkr  (b770a25)
- [x] `dag/clients.ts` containing `Client` type and client helpers @grgbkr  (https://github.com/rocicorp/replicache/commit/9533421da8c2dcd39a206bac26788f7e69e71ebc)

## Persist

See https://www.notion.so/MemDag-with-TempHash-e42058ee8f354e7e918c433cd92191fb?d=654c8bde3d1b4d4994792b65b7049352#3dae910d006646b0b3af44877a70a996

- [x] Make the hash function/chunk creation part of dag/db so that memdag and perdag can use different hashing strategies @arv
  - [x] Maybe also make the `assertNotTempHash` be `dagStore.isValidHash` @arv
  - [x] B+Tree cannot use isTempHash as a bit for mutable. @arv
- [x] Gather chunks from memdag @arv
- [x] Write chunks to perdag @arv
- [x] Compute hashes off the IDB transaction @arv
- [x] Fixup memdag @arv 
- [x] Glue it together @arv

## Heartbeats
- [x] Heartbeats @grgbkr  (https://github.com/rocicorp/replicache/commit/6b18ad07e3c3afd2978c8c37e0a57ae34c8d16c1)
- [x] Update heartbeat timestamp on persist @arv 
## Collecting Client-Side Client State
- [x] Collecting Client-Side Client State @grgbkr (https://github.com/rocicorp/replicache/commit/9a4a5100173ac577e167f5838c6b35d4a7b60cf1)
- ~~[ ] rocicorp/replicache#784~~ Punted to a follow up.
- ~~[ ] rocicorp/mono#121~~ Punted to a follow up. 

## Bootstrap
  - [x] Pick the "best" client @grgbkr (https://github.com/rocicorp/replicache/commit/981248bf0caefd60754db4a64eb59524250dda8b) 
  - [x] Be sure to reset lastMutationId to 0 @grgbkr  (https://github.com/rocicorp/replicache/commit/981248bf0caefd60754db4a64eb59524250dda8b)
  - [x] rocicorp/replicache#789

## Frozen and Throttled Tabs
 - [x] Pushing other tabs pending mutations @grgbkr (https://github.com/rocicorp/replicache/commit/1538c424e2369c36c5a41c7876f0dad338e59768)
 - ~~[ ] Rename `name` to `user`, keep deprecated name for a bit~~ Decided to not do this til V10
 - [ ] Add offline mental model and recipe (including how to do a dirty state prompt) https://www.notion.so/2022-01-20-241c0d01b5a44d6cb60d3304f3a25d5b#70361d8662994740a738797cf8f9b172  rocicorp/mono#123 @aboodman

## Collecting Server-Side Client State

Nothing to do here?
  - ~~[ ] rocicorp/replicache#335~~ Punted to a follow up

## Migrating Replicache

- [x] Include Replicache format version in the IDB database name rocicorp/replicache#741

TBD

## Migrating User Data

- [x] Include schemaVersion in the IDB database name rocicorp/replicache#741

TBD

## Perf
- [x] Document benchmark deltas vs existing indexdb and memstore
- [x] Write a start up benchmark, see perf envelope rocicorp/mono#134  @grgbkr (ce2baac)
- ~~[ ] Investigate scan performance~~ see https://github.com/rocicorp/replicache/issues/711 
- [x] Consider preloading chunks ahead of the scan cursor

## Other
- [x] Remove `useMemstore` in source @arv 
- [x] Remove `useMemstore` in docs
- [ ] rocicorp/mono#122
- [x] Update Replicache format version before releasing (0a38f9f297fbf8159a1029785f957550ed3ba6c8)
- [x] Update replidraw to use (this may happen automatically if replidraw uses memsore)
- [x] Remove old wasm based hash function @arv

**Comment by aboodman** [comment]
Calling this done, the rest will be separate bugs. 🎉
